name: GitSplit

on:
  push:
    branches:
      - 'main'
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+-**'

jobs:
  gitsplit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: git clone https://github.com/nbgrp/singlea ${{ github.workspace }} && cd ${{ github.workspace }}

      - name: Cache
        uses: actions/cache@v3.0.1
        with:
          path: /cache
          key: ${{ runner.os }}-gitcache

      - name: Split repositories
        uses: docker://jderusse/gitsplit:latest
        with:
          args: gitsplit
        env:
          GH_TOKEN: ${{ secrets.GITSPLIT_TOKEN }}
